spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/http-test
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
